version: '3'
services:
  cohort-atlas:
    build: .
    image: cohort-atlas:latest
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/cohortatlas?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./platform/keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8090:8080"

# avoid conflicts with EBI network
networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/16
