package uk.ac.ebi.biosamples.cohortatlas.harmonisation.gemini;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import dev.langchain4j.model.chat.ChatLanguageModel;
import org.springframework.core.io.ClassPathResource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

@RestController
public class ChatController {

  ChatLanguageModel chatLanguageModel;

  public ChatController(ChatLanguageModel chatLanguageModel) {
    this.chatLanguageModel = chatLanguageModel;
  }

//  @GetMapping("/chat")
  public String model1(@RequestParam(value = "message", defaultValue = "Hello") String message) {
    message = """
        You are a data harmonization AI. You have been given a standard dictionary with columns "TERM" and "DESCRIPTION" and\s
        an input data with columns "TERM" and "DESCRIPTION". Map each of the "TERM" in input data to a "TERM" in standard dictionary. Return mapping as a new key "MAPPING".
        
        Dictionary:
                                                                 TERM                                                                                                                                                                                                                                                                                                                                                        DESCRIPTION
                                                               saliva                                                                                                                                                                                                                                               A fluid produced in the oral cavity by salivary glands, typically used in predigestion, but also in other functions.
                                                          sample type                                                                                                                       Material anatomical entity in a gaseous, liquid, semisolid or solid state; produced by anatomical structures or derived from inhaled and ingested substances that have been modified by anatomical structures as they pass through the body.
                                       Microbiome markers (rRNA, etc)                                                                                                                                                                                                                                                                                              A genomic assay that profiles the microorganisms present in a sample.
                                                             genomics                                                                                                                                                                                                                                                             An assay that investigates the genome or genomes of an individual organism or population of organisms.
                                                life stage/time point                                                                                                                                                                                                                                                                                   A spatiotemporal region encompassing some part of the life cycle of an organism.
                                      other questionnaire/survey data                                                                                                                                                                                                                                                                                                                                                                NaN
                                         reproductive system diseases                                                                                                                                                                                                                                                                                                                       A disease involving the reproductive system.
                                                             diseases                                                                                                                                                                                                                         A disease is a disposition to undergo pathological processes that exists in an organism because of one or more disorders in that organism.
                                                   signs and symptoms                                                                                                                                                                                                                                A process experienced by the patient, which can only be experienced by the patient, that is hypothesized to be clinically relevant.
                                          circulation and respiration                                                                                                                                                                                                                                                                                                                                                                NaN
                                           physiological measurements                                                                                                                                                                                                                                                                                                                                                                NaN
                                            questionnaire/survey data                                                                                                                                                                                                                                                                                                                                                                NaN
                                                       blood pressure                                                                                                                                                                                                                                                                                                                                                                NaN
                                                            poisoning                                                                                                                                                                                                                                              A condition or physical state produced by the ingestion, injection, inhalation of or exposure to a deleterious agent.
                                                       DNA/Genotyping                                                                                                                                                An assay which generates data about a genotype from a specimen of genomic DNA. A variety of techniques and instruments can be used to produce information about sequence variation at particular genomic positions.
                                                    processing method                                                                                                                                                                                                                                                                                                A material processing which prepares a biosample for investigation.
                                                            biosample                                                                                                                                                                                                                                                                                                                                                                NaN
                                            endocrine system diseases                                                                                                                                                                                                                                                                                                                          A disease involving the endocrine system.
                                                          sample size                                                                                                                                                                                                                                                                                                A count of the number of biosamples collected for an investigation.
                                                  infectious diseases                                                                                                                                                                                                                A disorder resulting from the presence and activity of a microbial, viral, or parasitic agent. It can be transmitted by direct or indirect contact.
                                  eQTL (Cis eQTLs and/or Trans eQTLs)                                                                                                                                                                                                                                                                       A genomic assay that identifies genetic loci and candidate genes correlated with phenotypes.
                                                       administration                                                                                                                              A drug administration description that specifies a drug administration prescribed or reported by an healthcare provider. It specifies: - The drug product - The posology It may also specify a starting drug administration condition
                                                           medication                                                                                                                                                                                                                                                                                    A clinical history that is about the prescription drugs taken by an individual.
                                                         Metagenomics                                                                                                                                                                                      A DNA sequencing assay that intends to provide information on the DNA sequences of multiple genomes (a metagenome) from different organisms present in the same input sample.
                                              cardiovascular diseases                                                                                                                                                                                                                                                                                                                     A disease involving the cardiovascular system.
                             diseases of the ear, nose, and/or throat                                                                                                                                                                                                                                                                       Pathological processes of the ear, the nose, and the throat, also known as the ENT diseases.
                                                     hospitalizations                                                                                                                                                                                                                                                   an information content entity that is about a part of a health care encounter that occurs in a hospital facility
                                               healthcare information                                                                                                                                                                                                                                                                                          An information content entity about healthcare that is private or public.
                                                               weight                                                                                                                                                                                                                                                                                                                                                                NaN
                                                        anthropometry                                                                                                                                                                                                                                                                                                                                                                NaN
                                               immune system diseases                                                                                                                                                                                                                                                                                                     A disorder resulting from an abnormality in the immune system.
                                          personal beliefs and values                                                                                                                                                                                                                                                                                                                                                                NaN
                                                consent/accessibility                                                                                                                                                                                                                                                                         A textual entity that documents the consenting process used to enroll patients in a study.
                                                survey administration                                                                                                                                                                                                                                                                                                                                                                NaN
                                                               cancer A tumor composed of atypical neoplastic, often pleomorphic cells that invade other tissues. Malignant neoplasms often metastasize to distant anatomic sites and may recur after excision. The most common malignant neoplasms are carcinomas (adenocarcinomas or squamous cell carcinomas), Hodgkin and non-Hodgkin lymphomas, leukemias, melanomas, and sarcomas.
                                                  laboratory measures                                                                                                                                                                                                                                                                                                                                                                NaN
                                skin and subcutaneous tissue diseases                                                                                                                                                                                                                                                                                                                       A disease involving the integumental system.
                                                           birthplace                                                                                                                                                                                                                                                                                                           A geographical location in which an individual was born.
                       socio-demographic and economic characteristics                                                                                                                                                                                                                                                                                               A quality that inheres in an entire organism or part of an organism.
                                                       ethnicity/race                                                                                                                                                                   An organismal quality inhering in a bearer by virtue of the bearer's identification with a group of other individuals on the basis of presumed similarities such as language or common ancestry.
                                                               gender                                                                                                                                                                         An organismal quality inhering in a bearer by virtue of the bearer's preference towards a range of characteristics pertaining to, and differentiating between, masculinity and femininity.
                                                                  WGS                                                                                                                                                                                                                                                  A DNA sequencing assay that intends to provide information about the sequence of an entire genome of an organism.
                                                                  WES                                                                                                                                                                                                                                A DNA sequencing assay that intends to provide information about the sequence of the protein coding components of a genome (exons).
                                            physical activity history                                                                                                                                                                                                                                                                                  A lifestyle history that is about the typical physical activity of an individual.
                                             lifestyle and behaviours                                                                                                                                                                                                                                                    A clinical history that is about the lifestyle and behaviors of an individual which may impact health outcomes.
                                            recreational drug history                                                                                                                                                                                                                                                                           A lifestyle history that is about the use of unprescribed and/or non-prescription drugs.
                                                  alcohol use history                                                                                                                                                                                                                                                                                        A lifestyle history that is about the alcohol consumption of an individual.
        summary statistics for additional data from federated sources                                                                                                                                                                                                                                                                                                               A statistic that summarizes a set of federated data.
                                                           statistics                                                                                                                                                                                                                                                                                                                                                                NaN
                                                  tobacco use history                                                                                                                                                                                                                                                                                    A lifestyle history that is about the tobacco use or exposure of an individual.
                                              blood-related disorders                                                                                                                                                                                                                                                                                                                      A disease involving the hematopoietic system.
                                                         study design                                                                                                                                                         A plan specification comprised of protocols (which may specify how and what kinds of data will be gathered) that are executed as part of an investigation and is realized during a study design execution.
                                              basic cohort attributes                                                                                                                                                                                                                                                                                                                                                                NaN
                                       family and household structure                                                                                                                                                                                                                                                                                Information that is about the structure of an individual's family and/or household.
                                                            education                                                                                                                                                                                                                                                  An organismal quality inhering in a bearer by virute of the bearer's highest level of formal education completed.
                                                       biological sex                                                                                                                                                                                           An organismal quality inhering in a bearer by virtue of the bearer's ability to undergo sexual reproduction in order to differentiate the individuals or types involved.
                                                            residence                                                                                                                                                                                                                                                                                                  A geographical location in which an individual currently resides.
                                                              imaging                                                                                                                                                                                                                                                                                                                     An assay that produces a picture of an entity.
                                              urinary system diseases                                                                                                                                                                                                                                                                                                                              A disease involving the renal system.
                                                                stool                                                                                                                                                                                                                                                                                         Portion of semisolid bodily waste discharged through the anus[MW,modified]
                                    date and time-related information                                                                                                                                                                                                                                                                   Information about a calendar date or timestamp indicating day, month, year and time of an event.
                                               RNAseq/gene expression                                                                                                                                                                                                      An transcription profiling assay that determines an RNA sequence by analyzing the transcibed regions of the genome and or to quantitate transcript abundance.
                                                   unique identifiers                                                                                                                                                                                                                                                                        An identifier that is guaranteed to be unique among all identifiers in a particular domain.
                                             nervous system disorders                                                                                                                                                                                                                                                                 A non-neoplastic or neoplastic disorder that affects the brain, spinal cord, or peripheral nerves.
                                      musculoskeletal system diseases                                                                                                                                                                                                                                                                                                                    A disease involving the musculoskeletal system.
                                                     demographic data                                                                                                                                                                                                                                                                                                              A quality which inheres in a population of organisms.
                                             use of assistive devices                                                                                                                                                                                                                                                                         Information about an individual's use of assistive devices in performing daily activities.
                             perception of health and quality of life                                                                                                                                                                                                                                                                                                                                                                NaN
                                                    num. participants                                                                                                                                                                                                                                                                                     A sample size that is about the count of individual organisms in a population.
                                                      population data                                                                                                                                                                                                                                                                                                               A data item that is about a population of organisms.
                                               functional limitations                                                                                                                                                                                                                                                    Information that is about an individual's limitations in activities that involve caring for an moving the body.
                                                             location                                                                                                                                                                                                                                                                       A population data item that is about the geographical location of a population of organisms.
                                                      quality of life                                                                                                                                                                                                                                                                                A psychological measurement of an individual's perception of their quality of life.
                                                                urine                                                                                                                                                                                                                                                                                                                           Excretion that is the output of a kidney
                                               income and possessions                                                                                                                                                                                                                                                                                                                                                                NaN
                                              exposure to carcinogens                                                                                                                                                                                                                                          A information content entity that indicates the exposure of an individual to carcinogens in the workplace or environment.
                                                 physical environment                                                                                                                                                                                                                                                                                                  environmental system associated with the dwelling used by humans.
                   criteria for enrollment and recruitment procedures       an inclusion criterion (rule) is_a *eligibility criterion* which defines and states a condition which, if met, makes an entity suitable for a given task or participation in a given process. For instance, in a study protocol, inclusion criteria indicate the conditions that prospective subjects MUST meet to be eligible for participation in a study.
                                                 perception of health                                                                                                                                                                                                                                                                                    A psychological measurement of an individual's subjective perception of health.
                                       physical therapy interventions                                                                                                                                                                                                                                                 A non-pharmacological treatment history that is about physical therapy treatments such as physical rehabilitation.
                                    non-pharmacological interventions                                                                                                                                                                                                                                                         A treatment history that is about any non-pharamacological treatments such as surgery or physical therapy.
                                                             timeline                                                                                                                                                                                                                                                     A directive information entity that specifies the sequence in which a series of events occurred or will occur.
                                           radiological interventions                                                                                                                                                                                                                                             A non-pharmacological treatment history that is about use of radiology for treatment of disease, disorder, or symptom.
                                          psychological interventions                                                                                                                                                                                                                                                                A non-pharmacological treatment history that is about psychological treatments such as counselling.
                                                  oral health history                                                                                                                                                                                                                                                                                                         A lifestyle history that is about oral health and hygiene.
                                  psychological distress and emotions                                                                                                                                                                                                                                                     A biological process that results from neurophysiological changes in response to internal and external events.
                             cognitive and psychological measurements                                                                                                                                                                                                                                                                                                            A measurement datum of some aspect of human psychology.
                                                          personality                                                                                                                                                                                                                                                       A psychological measurement of a person's individual sets of behaviours, cognitions, and emotional patterns.
                                       mental and behaviour disorders                                                                                                                                                                                                                                                                                                  A disease that has its basis in the disruption of mental process.
                                                cognitive functioning                                                                                                                                                                                                                                           A psychological measurement of some aspect of intellectual functions such as memory, problem solving, and comprehension.
                                                           occupation                                                                                                                                                                                                                                            An information content entity that is about an activity that realizes a social role and is often performed for payment.
                                          physician/practitioner info                                                                                                                                                                                                                                 A textual entity that contains contact details for an individual's physician, which may include: name, phone number, address, etc.
                                                      dietary history                                                                                                                                                                                                                                                                                         A lifestyle history that is about the diet and nutrition of an individual.
                                                      heart rate (HR)                                                                                                                                                                                                                                                                                                                                                                NaN
                                                        sleep history                                                                                                                                                                                                                                                                                 A lifestyle history that is about the sleep quality and duration of an individual.
                                                         reproduction                                                                                                                                                                                                                                                       A clinical history that is about pregnancy, maternity, fertility, menses, and any other reproductive aspect.
                                                         availability                                                                                                                                                                                                                                                                           An availability textual entity that is about a substance from an organism (a biosample).
                                                 other biosample type                                                                                                                                                                                                                                                                                                                                                                NaN
                                                          Epigenetics                                                                                                                                                                                                                                            An assay that identifies epigenetic modifications including histone modifications, open chromatin, and DNA methylation.
                                                         prescription                                                                                                                                                                                                                                                          A health care prescription specifying the initiation, modification or cessation of a drug administration.
                                          respiratory system diseases                                                                                                                            A non-neoplastic or neoplastic disorder that affects the respiratory system. Representative examples include pneumonia, chronic obstructive pulmonary disease, pulmonary failure, lung adenoma, lung carcinoma, and tracheal carcinoma.
                                              routine clincial visits                                                                                                                                                                                                                         a data item that is about an investigation and is the specified output of a data transformation that has only clinical visit data as input
                                                       cause of death                                                                                                                                                                                                                                                                        An information content entity indicating the cause of death for a participant in the study.
                                                                blood                                                                                                                                                                                                                                                                                                         A fluid that is composed of blood plasma and erythrocytes.
                                     congenital and genetic disorders                                                                                                                                                                                                                                                                   A disorder that is present at birth due to genetics or environmental factors during development.
                                               visual system diseases                                                                                                                                                                                                                                                                                                                         A disease that involves the visual system.
                                                         microbiology                                                                                                                                                                                                                                                                                                       An assay that identifies the organism species in a specimen.
                                                       storage method                                                                                                                                                                                                                                                                                                      A storage process for a biosample collected from an organism.
                                                               height                                                                                                                                                                                                                                                                                                                                                                NaN
                                                                  CDR                                                                                                                                                                                                                                                                        A cognitive measurement that is the output (score) from the Clinical Dementia Rating Scale.
                                                                  NPI                                                                                                                                                                                                                                                                            A cognitive measurement that is the output (score) from the Neuropsychiatric Inventory.
                                                                  SIB                                                                                                                                                                                                                                                                             A cognitive measurement that is the output (score) from the Severe Impairment Battery.
                                                        age/birthdate                                                                                                                                                                                                                                                                                  A time quality inhering in a bearer by virtue of how long the bearer has existed.
                                                  aims and objectives                                                                                                          A directive information entity that describes an intended process endpoint. When part of a plan specification the concretization is realized in a planned process in which the bearer tries to effect the world so that the process endpoint is achieved.
                                                       marital status                                                                                                                                                                                                                  a categorical value specification that is about a human being and specifies whether that human being is joined to another human being in marriage
                                               fasting or non-fasting                                                                                                                                                                                                                                                                        Blood that is collected from an organism which has been fasting for a given amount of time.
                                                             Penn CNB                                                                                                                                                                                                                                                              A cognitive measurement that is the output (score) from the Penn Computerized Neurocognitive Battery.
                                  Sequence variants (CNV, SNP arrays)                                                                                                                                        An assay that determines lost or amplified genomic regions of DNA by comparing genomic DNA originating from tissues from the same or different individuals using specific techniques such as CGH, array CGH, SNP genotyping
                                                        CERAD Battery                                                                                                                                                                                                                                                                     A cognitive measurement that is the output (score) from the CERAD Neurophyschological Battery.
                                                     drug response(s)                                                                                                                                                                                                                                                                                                            A biological process that results from a drug stimulus.
                                                associated disease(s)                                                                                                                                                                                                                                                                               Information that is about the disease treated by a drug prescribed to an individual.
                                               surgical interventions                                                                                                                                                                                                                                                                                   A clinical history that is about surgical operations performed on an individual.
                                            digestive system diseases                                                                                                                                                                                                                                                                                                          A disease or disorder that involves the digestive system.
                                                                 MoCA                                                                                                                                                                                                                                                 A cognitive measurement that is the output (score) from the Montreal Cognitive Assessment Test (MoCA) for Dementia
                                                      native language                                                                                                                                                                                                                                                           Information about the language an individual has been exposed to from birth and is their first language.
                                                                 MMSE                                                                                                                                                                                                                                                                                 A cognitive measurement that is an output (score) from the Mini-Mental State Exam.
                                                                 ADAS                                                                                                                                                                                                                                                                   A cognitive measurement that is an output (score) from the Alzheimer's Disease Assessment Scale.
                                               data collection events                                                                                                                                                                                                                                                                               A planned process that is a part of an investigation in which raw data is collected.
                                             diagnostic interventions                                                                                                                                                                                                                                                   A non-pharmacological treatment history that is about diagnostic procedures to determine a condition or disease.
                                                            age range                                                                                                                                                                                                                                                                                                     A population quality concerning the age range of a population.
                                                             injuries                                                                                                                                                                                                                           Damage inflicted on the body as the direct or indirect result of an external force, with or without disruption of structural continuity.
                                            family history of disease                                                                                                                                                                                                                                                                                                    A clinical history that is about any family history of disease.
                                          gender(s) studied in cohort                                                                                                                                                                                                                                                                                           A population quality concerning the gender or genders of the population.
                                                   social environment                                                                                                                                                                     An immaterial entity that encompasses the domain made up of interactions between the individual's physical environment, social processes, and relationships with other individuals and groups.
                                            sex(es) studied in cohort                                                                                                                                                                                                                                                                                                A population quality concerning the sex or sexes of the population.
                                                             religion                                                                                                                                                                                                                                         Information about an individual's association with a religion, denomiation, or sub- or non-denominational religious group.
        
        Input Data:
                  TERM    DESCRIPTION
                Gender         Gender
             Birthdate      Birthdate
         Year of birth  Year of birth
        Agreement date Agreement date
        Age at present Age at present
        
        Provide the harmonized output as a JSON list.
        
        """;
    return chatLanguageModel.chat(message);
  }

  @GetMapping("/chat")
  public List<HarmonisingField> model(@RequestParam(value = "message", defaultValue = "Hello") String message) {
    String dictionary = readFildAndGetAsJsonString("mapping/standard_terms.csv");
    String input = readFildAndGetAsJsonString("mapping/annotate_me.csv");
    message = """
        You are a data harmonization AI. You have been given a standard dictionary with columns "TERM" and "DESCRIPTION" \\
        and an input data with columns "TERM" and "DESCRIPTION". Map each of the "TERM" in input data to a "TERM" in \\
        standard dictionary. Return mapping as a new key "MAPPING".
        
        Dictionary:
        %s                                                                                                                                                                                                                                                                                              Information about an individual's association with a religion, denomiation, or sub- or non-denominational religious group.
        
        Input Data:
        %s
        
        Provide the harmonized output as a JSON list.
        
        """.formatted(dictionary, input);
    String out = chatLanguageModel.chat(message);
//    String out = "";
    try {
      List<HarmonisingField> list = new ObjectMapper().readValue(out.substring(8, out.length() - 3), new TypeReference<>() {
      });
      return list;
    } catch (JsonProcessingException e) {
      throw new RuntimeException(e);
    }
  }

  private String readFildAndGetAsJsonString(String fileName) {
    ObjectMapper objectMapper = new ObjectMapper();
    CsvMapper mapper = new CsvMapper();

//    CsvSchema csvSchema = mapper
//        .typedSchemaFor(HarmonisingField.class)
//        .withHeader()
//        .withColumnSeparator(',')
//        .withComments();

//    CsvSchema csvSchema = CsvSchema
//        .builder()
//        .addColumn("TERM")
//        .addColumn("DESCRIPTION")
//        .build()
//        .withHeader()
//        .withColumnSeparator(',')
//        .withComments();

    CsvSchema csvSchema = CsvSchema.emptySchema().withHeader().withColumnSeparator(',').withComments();


    try {
    InputStream in = new ClassPathResource(fileName).getInputStream();
    MappingIterator<HarmonisingField> csvIterator = mapper.readerWithTypedSchemaFor(HarmonisingField.class).with(csvSchema)
        .readValues(in);
      List<HarmonisingField> dictionary = csvIterator.readAll();
      return objectMapper.writeValueAsString(dictionary);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }
  }


}
